# In scBOA/.github/workflows/run_test.yml
name: scBOA Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download a small CellTypist model for testing
      run: |
        pip install wget
        python -c "import wget; url = 'https://celltypist.s3.eu-west-2.amazonaws.com/models/Pan_Fetal_Human/v2/Immune_All_Low.pkl'; wget.download(url)"

    - name: Run a quick test of scBOA.py
      run: |
        python scBOA.py \
          --data_dir ./example_data/ \
          --output_dir ./test_output/ \
          --model_path ./test_assets/Healthy_COVID19_PBMC.pkl \
          --n_calls 1 \
          --target weighted_cas \
          --min_genes 1 \
          --min_cells 1 \
          --seed 123
